In [2]:
import numpy as np

# ARITHMETIC OPERATIONS

In [6]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [7]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [8]:
a1-a2

array([-5, -5, -5, -5, -5])

In [9]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [10]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
a1//a2

array([0, 0, 0, 0, 0])

In [12]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

# BROADCASTING

In [13]:
l = [10,20,30,40]
arr = np.array(l)

In [14]:
arr+10

array([20, 30, 40, 50])

In [16]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [18]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

# DEEP AND SHALLOW COPY

In [29]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [31]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
a
b=a.copy()

In [38]:
b[0] = 99

In [39]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# MATRIX OPERATION

In [43]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [44]:
A

array([[1, 2],
       [3, 4]])

In [45]:
B

array([[5, 6],
       [7, 8]])

In [46]:
A@B

array([[19, 22],
       [43, 50]])

In [47]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [48]:
A.T

array([[1, 3],
       [2, 4]])

# ADVANCE ARRAY MANIPULATION

In [49]:
# Stacking Array
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [51]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [54]:
# Spliting Array
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [58]:
a =np.vsplit(c,2)
a

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [59]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
