In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40])
mask = arr > 25

In [3]:
mask

array([False, False,  True,  True])

In [4]:
filtered = arr[mask]
print(filtered)

[30 40]


In [5]:
arr = np.array([5,12,18,25,30])
result = arr[arr >= 18]
print(result)

[18 25 30]


In [6]:
arr = np.array([5,12,18,25,30])
result = arr[(arr>15)&(arr<30)]
print(result)

[18 25]


In [8]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr[arr>3])

[4 5 6]
