In [2]:
import numpy as np

BASIC ARRAY CREATION

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1,2,3,3.5, "hello"]
a

[1, 2, 3, 3.5, 'hello']

In [5]:
np.array(a)

array(['1', '2', '3', '3.5', 'hello'], dtype='<U32')

In [6]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ARRAY GENERATION FUNCTION

In [8]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [9]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [11]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
arr = np.linspace(0,5,4)
arr

array([0.        , 1.66666667, 3.33333333, 5.        ])

RANDOM GENERATION FUNCTION

In [14]:
np.random.rand(10)

array([0.95261699, 0.55172462, 0.87302335, 0.48362319, 0.83766853,
       0.66743888, 0.58639897, 0.57124069, 0.90699659, 0.33854772])

In [15]:
np.random.randn(10)

array([-0.35522199,  0.60457017, -0.06609001, -0.2828516 , -0.03038515,
        1.01566164,  2.55672779, -0.34925177, -0.42652032,  0.15298157])

In [16]:
np.random.randint(10,20,10)

array([14, 11, 13, 11, 11, 17, 17, 11, 11, 13], dtype=int32)

ARRAY ATTEIBUTES

In [17]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int64')

ARRAY METHOD

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(9)

In [24]:
arr.sum()

np.int64(45)

In [25]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [26]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [27]:
arr.mean()

np.float64(5.0)

In [28]:
arr.std()

np.float64(2.581988897471611)

In [29]:
arr.argmax()

np.int64(8)

In [30]:
arr.argmin()

np.int64(0)

RESHAPING AND RESIZING

In [32]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])