In [1]:
import numpy as np

ELEMENT WISE OPERATIONS 

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
# res = arr1*arr2
# res = arr1+arr2
# res = arr1-arr2
res = arr1/arr2
print(res)

[0.2        0.33333333 0.42857143 0.5       ]



SCALER OPERATION

In [4]:
res = arr1*3
print(res)

[ 3  6  9 12]



COMPARISION OPERATION

In [5]:
res = arr1<arr2
print(res)

[ True  True  True  True]



DOT PRODUCT

In [8]:
matrix1 = np.array([[3,4,5],[3,5,1],[5,6,7]])
matrix2 = np.array([[2,3,4],[4,5,7],[4,4,3]])
print(matrix1*matrix2)
print(np.dot(matrix1,matrix2))

[[ 6 12 20]
 [12 25  7]
 [20 24 21]]
[[42 49 55]
 [30 38 50]
 [62 73 83]]



MATH FUNCTION

In [10]:
a = np.array([0,np.pi/4,np.pi])
print(np.sin(a))
print(np.cos(a))

[0.00000000e+00 7.07106781e-01 1.22464680e-16]
[ 1.          0.70710678 -1.        ]
